### PR TITLE
Add missing commas, correction of spelling errors

### PR DESCRIPTION
**Pull request by patsevanton**
Add missing commas, correction of spelling errors

### CODE REVIEW

**Comment by thavlik** [comment]
Greetings Anton! Thank you kindly for the pull request, and I am happy to approve it.

Regarding the comma correction, this is an interesting situation. As a native English speaker with a college education, I can assure you the original sentence is *technically* correct, although colloquial. I had omitted the word "that", as in the following:

> If you have real VPN credentials [that] you want to use in the tests, specify the environment variables `SECRET_NAME` and `SECRET_NAMESPACE` to point to the in-cluster `Secret` resource containing the credentials.

Your suggestion gives me valuable insight into how people parse this sentence. If it's not obvious to you that the original uses correct grammar, this is my cue to rewrite it with shorter and simpler language. I will rewrite this bit in sentences of no more than fifteen words. Limiting sentence length in this way tends to generate clear language.

I took the liberty of peeking at your GitHub profile. Привет. I read & write Russian at an A2 level. The Russian language's use of the comma is very tasteful to me—it really does make the formation of complex ideas easier. If I had written this sentence to be amenable to the Russian comma, it'd be much easier to understand, even for native speakers. I am actively seeking to optimize my technical writing for clarity, so thanks for bringing this to my attention. Moving forward, I will try and make it easier for readers to imagine Russian commas. A wise man once said that if you do not know a second language, you know nothing of your own!

Best,

Tom

**Comment by patsevanton** [comment]
Thanks! I'm trying to be helpful.

**Comment by thavlik** [comment]
You are doing a fantastic job and I'm happy to have you as a contributor on this project. Best of luck to you!

**Comment by thavlik** [comment]
@patsevanton FYI I have many other projects here on GitHub that you are more than welcome to contribute to. Reviewing and improving the clarity of documentation and/or code is extremely helpful. As a native speaker, I am blinded to the complexity of my own language. There are also other DevOps tasks that are available, for this project and others.

Some projects have a bot that comments on pull requests with an error message if `rustfmt` modifies any of the source code. This ensures only consistently formatted code is merged. Would you be interested in adding such a feature to this project? I can provide examples if necessary.

It would also be cool to have tests automatically run for each commit. Since it's a k8s app, I'll have to put more thought into how I'd like to see this implemented. It doesn't seem wise to give pull requests from strangers access to a cluster 😉

Tom

**Comment by patsevanton** [comment]
I don`t know Rust.

**Comment by thavlik** [comment]
You don't need to know rust for some of this. `rustfmt` is a command line utility that will format the code. The exact command that will be used is `rustfmt --edition 2018 --check operator/src/main.rs` and if any of the files are modified, the command will fail with exit code 1. This is how it is utilized as a commit hook, and this paradigm is the same across all languages.

**Pull request merged**
